[package]
name = "gst-webrtc"
version = "0.0.0"
edition = "2024"

[dependencies]
gst-plugin-rtp = { version = "0.13.5", default-features = false }
gst-plugin-webrtc = { version = "0.13.5", default-features = false, features = ["v1_22"] }
